"""
Release draft generation

### Step 1 (Initial draft layout)
- generate new draft for new upcoming release by running this script

### Step 2 (Team adds highlights)
- ask all team members to review and pick items that are worthy of a highlight

### Step 3 (cleanup before submission to `product owners`, like the App Team)
- ensure system capacity is increased during testing to have the environment more colser to production
- remove link of the avialable PRs before submitting to App Team
- NOTE: app team is not interested in the What's Changed section generated by GitHub
"""

from pathlib import Path

from utils import INITIALS_TO_USERNAMES, list_folders_in_path, require_tag_from_cli

CURRENT_DIR: Path = Path(__file__).resolve().parent

INITIALS: list[str] = list(INITIALS_TO_USERNAMES.keys())

_TEMPLATE: str = """Click on the link for a list of all the PRs released since `{version_tag}`
https://github.com/ITISFoundation/osparc-simcore/compare/{version_tag}...master

Please check your name if finished:
{names_to_check}

**Draft release notes go below the line**
---
"""


_MATTERMOST_TEMPLATE: str = """
@all please contribute in compiling the `Release Drafts`.
There are 3 release drafts to fill out: `s4l` (which also includes s4li-lite), `osparc`, `tip`.
Instructions:
- Please go through all your last changes in master since the last release for each product: [osparc](https://github.com/ITISFoundation/osparc-issues/blob/master/release-notes/osparc/{version_tag}.md), [s4l](https://github.com/ITISFoundation/osparc-issues/blob/master/release-notes/s4l/{version_tag}.md) and [tip](https://github.com/ITISFoundation/osparc-issues/blob/master/release-notes/tip/{version_tag}.md) (each product contains a link to these changes)
- For each product please chose those features which it makes sense to highlight.
- When highlighting a feature please provide a meaningful `USER` readable description and the link to the PR
- deadline `MM.DD by HH:MM`
- please :white_check_mark: your name when done in all products so I can keep track of who is missing.

:pray: Thanks everybody for your kind cooperation and help.
"""


def _get_previous_version(vtag: str) -> int:
    version_parts = vtag.strip("v").split(".")
    version_parts[1] = f"{int(version_parts[1])-1}"

    return "v" + ".".join(version_parts)


def _get_names_to_check() -> str:
    return "\n".join([f"- [ ] {name}" for name in INITIALS])


def main():
    tag = require_tag_from_cli()
    vtag = f"v{tag}"

    print("\nTotal [STEPS] 2\n")

    print(f"Will generate form tag: {vtag}")

    new_draft_content = _TEMPLATE.format(
        version_tag=_get_previous_version(vtag), names_to_check=_get_names_to_check()
    )
    for product_folder in list_folders_in_path(CURRENT_DIR / ".." / "release-notes"):
        draft_file = product_folder / f"{vtag}.md"
        if draft_file.exists():
            msg = f"{draft_file} already exists, make sure you are creating the draft for the correct release"
            raise ValueError(msg)
        draft_file.write_text(new_draft_content)

    print(
        "\n[STEP] 1/2 post this message on mattermost, please edit the DEADLINE accordingly\n"
    )
    print(_MATTERMOST_TEMPLATE.format(version_tag=vtag))

    print("\n[STEP] 2/2 commit and push changes generated in this repo!!!!\n")


if __name__ == "__main__":
    main()
